# -*- coding: utf-8 -*-
{
    'name': 'Application Vehicules',
    'version': '1.0',
    'description': """ Module permettant de gérer la flotte de véhicules""",
    'category': 'Customizations',
    'website': 'https://www.votreentreprise.com',
    'depends': ['base', 'mail','hr'],
    'application':True,
    'data':[
        'security/ir.model.access.csv',
        'views/document.xml',
        'views/parcVehicule1.xml',
        'views/maintenance.xml',
        'views/affectation.xml',
        'views/demande_vehicule.xml',
        'views/pays.xml',
        'views/agence.xml',
        # 'views/depatement.xml',
        'views/direction.xml',
        'views/service.xml',
        #'views/res_user.xml',
        'views/dashbord.xml',
        'views/parcVehicule.xml',
    ],
}